### ISSUE TITLE
Agregar ayuda en preguntas

### ISSUE THREAD

**Issue by sergioviera** [UTN-FRD/tutorias#10]
En las preguntas, agregar un nuevo campo para cargar un texto que oriente al usuario al cargar la respuesta.

por ejemplo: 
Pregunta: Ingrese el DNI
Texto mostrado debajo del input: "ingresar el número sin puntos"

Pregunta: Telefono
Texto mostrado debajo del input: "ingresar codigo de área"

**Comment by JuanBono** [comment]
Ahi lo agregue pero se ve con letra roja.

**Comment by juanbono** [comment]
Solucionado :D

**Comment by sergioviera** [comment]
:smiley:

**Comment by jacricelli** [comment]
Falta la columna `Ayuda` en el listado de preguntas y no es posible editar el campo `Ayuda`.

**Comment by sergioviera** [comment]
testing ok
