### ISSUE TITLE
Regenerar encuesta

### ISSUE THREAD

**Issue by sergioviera** [UTN-FRD/tutorias#14]
Agregar la opción de regenerar encuesta a un alumno, 
Poner este botón dentro de la edición del alumno.

Al regenerar una encuesta se debe alertar al usuario de que se eliminará la encuesta anterior.

**Comment by juanbono** [comment]
Ahi lo agregue, me quedo la duda si queda mejor que la opcion este en la encuesta o en el index de estudiantes junto a editar,borrar y encuesta.

**Comment by sergioviera** [comment]
NO, dentro de la encuesta y ahora que lo pienso deberia ser mejor utilizado sólo por el administrador.

Si lo ponemos en la tabla, al lado de los otros botones, puede activarse por error.

**Comment by juanbono** [comment]
Ahh ok, ahi me fije que tengo que chequear que la pregunta no exista para crearla. Ahi lo arreglo y lo subo

**Comment by sergioviera** [comment]
me da un error al regenerar una encuesta
![image](https://cloud.githubusercontent.com/assets/831628/9238821/d3375538-412b-11e5-86fb-7d753ca766f4.png)
