### ISSUE TITLE
Cargar nombre de alumno

### ISSUE THREAD

**Issue by sergioviera** [UTN-FRD/tutorias#15]
Al ingresar un alumno sólo se permite ingresar letras, no permitiendo espacios, comas y letras con acentos.

**Comment by matiasm15** [comment]
Recien lo probe y puedo agregar nombres con espacios y acentos. Quizas tenes una versión vieja porque yo solucione eso unos commits atras.

**Comment by sergioviera** [comment]
Si, puede ser, este issue lo tomé de la versión que está instalada en el
server (el de producción).

Estaria bueno, si te animás vos o pedirle a Jorge el Miercoles, que suban
los últimos cambios.
