### ISSUE TITLE
No mostrar las query en las pantallas

### ISSUE THREAD

**Issue by sergioviera** [UTN-FRD/tutorias#2]
Antes del footer en la mayoria de las páginas, se muestra información de la query que se realizó en la base de datos:
![image](https://cloud.githubusercontent.com/assets/831628/6648416/29204a4a-c9b8-11e4-86d0-1db9910d280f.png)

No mostrar esto en las páginas.

**Comment by jacricelli** [comment]
Eso es parte del [modo depuración](https://github.com/UTN-FRD/tutorias/blob/master/app/Config/core.php#L34) y mientras estén desarrollando no sería bueno ocultarlo. Pueden utilizar [DebugKit](https://github.com/cakephp/debug_kit) que es una alternativa más completa.

**Comment by sergioviera** [comment]
Genial, o sea que se puede cambiar en el server y listo, no? Gracias por el
tip!

2015-03-14 9:29 GMT-03:00 Jorge Alberto C. notifications@github.com:

**Comment by sergioviera** [comment]
para esto hay que modificar el segundo parametro de 

```
Configure::write('debug', 2);
```

tal como se indica en el archivo app/Config/Schema/core.php
