### ISSUE TITLE
Activar Menu Usuarios

### ISSUE THREAD

**Issue by sergioviera** [UTN-FRD/tutorias#20]
Cuando se accede a la pantalla de usuarios (http://localhost/tutorias/users) el menu no queda activo.

**Comment by matiasm15** [comment]
Esta es la issue que no había entendido. No encuentro ningun error en la pantalla de usuarios.

**Comment by sergioviera** [comment]
Este era un problema menor, cuando se accede a un menú, el menú debe quedar activo, o sea, de alguna manera mostrar que ese menú es el que está mostrandose.

Dejame que lo veo desde la facu y me fijo si ya no fué solucionado.
