### ISSUE TITLE
Setear el usuario en el navbar

### ISSUE THREAD

**Issue by sergioviera** [UTN-FRD/tutorias#3]
Actualmente se muestra en la barra de menues la palabra "Usuario", reemplazar la misma con el nombre del usuario.

**Comment by juanbono** [comment]
Ya esta solucionado. Tambien agregue para que el boton Perfil dirija a "/tutorias/users/edit" y logout a "/tutorias/users/logout"

**Comment by sergioviera** [comment]
:ok_hand:
