### ISSUE TITLE
Edicion de Usuario

### ISSUE THREAD

**Issue by sergioviera** [UTN-FRD/tutorias#4]
Crear vista para la edicion del usuario (el controlador está creado, pero hay que hacerle una pequeña modificación).

La edicion de usuario se debe acceder desde el menu "[Nombre de usuario]->Perfil" en la barra superior.

En el controlador, modificar para que si el usuario no es administrador, se muestre sólo el perfil de él, esto es, setear el valor de $id por el id del usuario logeado.

**Comment by juanbono** [comment]
Es decir que si el usuario no es administrador no puede editar su perfil, solo ver los datos?

**Comment by sergioviera** [comment]
No, la idea es la siguiente:
- Si el usuario es administrador, puede ver y editar cualquier otro usuario.
- Si el usuario NO es administrador, sólo puede ver y editar su perfil.

Ahora, hay que asegurarse que si un usuario NO es administrador, no pueda acceder por URL al perfil de otro usuario, por eso la aclaración de setear el $id.

**Comment by sergioviera** [comment]
la parte visual ya está solucionado, pero hay que estar seguros que no pueda acceder por url

**Comment by sergioviera** [comment]
funciona OK
