### ISSUE TITLE
Restringir menues

### ISSUE THREAD

**Issue by sergioviera** [UTN-FRD/tutorias#6]
Los menues de usuario/tutores y preguntas, sólo puede ser accedido por el usuario administrador.

**Comment by juanbono** [comment]
Los menues serian agregar/editar/borrar ? O directamente un tutor no tiene que ver la lista con los demas tutores?.
Lo que hice fue seguir el tutorial del blog, ya que era parecido al tema del admin y los autores. Quedo como que los usuarios de tipo admin pueden realizar todas las acciones y los tutores solo ver las listas de preguntas / tutores. ¿Estaria bien asi?

**Comment by sergioviera** [comment]
Claro, no tiene que ver los demas tutores, eso lo va a ver únicamente el
administrador.

2015-03-15 4:49 GMT-03:00 Juan Bono notifications@github.com:

**Comment by sergioviera** [comment]
Si creo un usuario administrador y un usuario tutor, ambos pueden realizar todas las acciones.

**Comment by sergioviera** [comment]
Los menues ya no se muestran, pero puedo acceder por url a una acción no permitida para un tutor (por ejemplo al listado de preguntas)

**Comment by juanbono** [comment]
Ahh buenisimo, en ambas issues queda mas o menos lo mismo, este finde veo de terminarlo. :D

**Comment by sergioviera** [comment]
testing OK
